#:schema node_modules/wrangler/config-schema.json
name = "my-bt-navigator"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[vars]
# Add your environment variables here if needed
# NEXT_PUBLIC_SUPABASE_URL = "..."
